services:
  web:
    build:
      context: .
      dockerfile: extras/docker/production/Dockerfile
    container_name: wger_web
    depends_on:
      - db
      - cache
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-change-this-to-a-random-secret-key}
      - SITE_URL=${SITE_URL:-http://localhost}
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD:-wger}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      - DJANGO_CACHE_TIMEOUT=1800
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient
      - CELERY_BROKER=redis://cache:6379/2
      - CELERY_BACKEND=redis://cache:6379/2
      - DJANGO_PERFORM_MIGRATIONS=True
      - WGER_USE_GUNICORN=True
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
      - ALLOW_REGISTRATION=${ALLOW_REGISTRATION:-True}
      - ALLOW_GUEST_USERS=${ALLOW_GUEST_USERS:-True}
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: wger_nginx
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/home/wger/static:ro
      - media:/home/wger/media:ro
    ports:
      - "80:80"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: wger_db
    environment:
      - POSTGRES_DB=${DJANGO_DB_DATABASE:-wger}
      - POSTGRES_USER=${DJANGO_DB_USER:-wger}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD:-wger}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis:7-alpine
    container_name: wger_cache
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: extras/docker/production/Dockerfile
    container_name: wger_celery_worker
    command: /start-worker
    depends_on:
      - web
      - cache
      - db
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-change-this-to-a-random-secret-key}
      - SITE_URL=${SITE_URL:-http://localhost}
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD:-wger}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      - DJANGO_CACHE_TIMEOUT=1800
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient
      - CELERY_BROKER=redis://cache:6379/2
      - CELERY_BACKEND=redis://cache:6379/2
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
    volumes:
      - media:/home/wger/media
    healthcheck:
      test: ["CMD-SHELL", "celery -A wger inspect ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: extras/docker/production/Dockerfile
    container_name: wger_celery_beat
    command: /start-beat
    depends_on:
      - celery_worker
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-change-this-to-a-random-secret-key}
      - SITE_URL=${SITE_URL:-http://localhost}
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=${DJANGO_DB_DATABASE:-wger}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-wger}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD:-wger}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      - DJANGO_CACHE_TIMEOUT=1800
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient
      - CELERY_BROKER=redis://cache:6379/2
      - CELERY_BACKEND=redis://cache:6379/2
      - TIME_ZONE=${TIME_ZONE:-Europe/Berlin}
    volumes:
      - celery-beat:/home/wger/beat
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  static:
  media:
  celery-beat:
